# GENERAL APP SETTINGS
spring.application.name=citylibraryapp
spring.main.banner-mode=off
logging.level.root=info

# Active Spring Profile setting
# TODO Change this to 'prod' before deploying app to production
spring.profiles.active=dev
