# DEVELOPMENT ENVIRONMENT PROPERTIES

# LOCAL DEV DATABASE CONFIG SETTINGS
spring.config.import=optional:local_dev_database_config.properties

# JPA/Hibernate Settings
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
